### ISSUE TITLE
dedit.d(4): Error: variable dedit.g default construction is disabled for type Terminal

### ISSUE THREAD

**Issue by eresid** [guitarxhero/dedit#1]
![2016-07-18 22-13-55](https://cloud.githubusercontent.com/assets/3881790/16927207/faf803fe-4d34-11e6-9120-7dffe55b75e6.png)

**Comment by guitarxhero** [comment]
Oh hello! Never thought anyone would _actually_ pay attention to this.

Story is, I started this (experiment with stuff for not even a dozen of lines) then quickly decided to make a [C# port](https://github.com/guitarxhero/dedit-cs) to get a better overview of things (also since C# is my first language).

However if people are actually wanting this instead, I'll start working on it.

The issue is that `terminal.d` is kind of incomplete (missing colors), and a struct without a default constructor can't be initiated as a static variable (available to all methods) which are things I planned to change.

I hope the future people will be patient!

I'll leave this open because it's an actual issue.

**Comment by guitarxhero** [comment]
Actually figured out to work around that, woo.
